Website/Models/Payments/PaymentCredentials.cs
using System.ComponentModel.DataAnnotations;

namespace EMovies.Models.Movies
{
    public class PaymentCredentials
    {
        [Required]
        [RegularExpression(@"^\w{1,40}$", ErrorMessage = "Please keep your name within 40 characters.")]
        public string Name { get; set; }
        
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [RegularExpression(@"^\d{14,18}$", ErrorMessage = "Please enter a valid Card Number.")]
        public string CardNumber { get; set; }

        public bool EmailNotification { get; set; }

        public enum CardIdentifier
        {
            Visa = 1,
            MasterCard = 2,
            AmericanExpress = 3
        }

        [Required]
        [RegularExpression(@"[^0]+", ErrorMessage = "Please enter a valid Card Type.")]
        [Key]
        public CardIdentifier CardType { get; set; }
    }
}

Website/Models/Payments/PaymentPageItems.cs
namespace Website.Models.Payments
{
    public class PaymentPageItems
    {
        public static string HomeItem = "/sitecore/Content/Payment";
        public static string UpdatedPaymentItem = "/sitecore/Content/UpdatedPayment";
        public static string SummaryItem = "/sitecore/Content/Summary";
    }
}

Website/Controllers/PaymentsController.cs
using EMovies.Models.Movies;
using System.Web.Mvc;
using Website.Models.Movies;
using Website.Models.Payments;

namespace EMovies.Controllers
{
    public class PaymentsController : Controller
    {
        private PaymentCredentials EmptyPayment()
        {
            return new PaymentCredentials
            {
                Name = string.Empty,
                Email = string.Empty,
                CardNumber = string.Empty,
                EmailNotification = false,
            };
        }

        public ActionResult Payment()
        {
            ShoppingBasket basket = (ShoppingBasket)Session["Basket"];

            if (basket == null)
            {
                return Redirect(BrowsePageFunctions.GetUrlForItem(BrowsePageConstants.HomeItem));
            }
            else
            {
                PaymentCredentials payment = (PaymentCredentials)Session["newPayment"];

                if (payment == null)
                {
                    return View(EmptyPayment());
                }
                else
                {
                    TryUpdateModel(payment);
                    return View(payment);
                }
            }
        }

        public ActionResult SubmitPayment(PaymentCredentials payment)
        {
            Session["newPayment"] = payment;
            if (!ModelState.IsValid)
            {
                return Redirect(BrowsePageFunctions.GetUrlForItem(PaymentPageItems.HomeItem));
            }
            else
            {
                return Redirect(BrowsePageFunctions.GetUrlForItem(PaymentPageItems.SummaryItem));
            }
        }
    }
}

Website/Views/Payments/Payment.cshtml
@model EMovies.Models.Movies.PaymentCredentials

    <html>
    <head>
        <META Http-Equiv="Cache-Control" Content="no-cache" />
        <META Http-Equiv="Pragma" Content="no-cache" />
        <META Http-Equiv="Expires" Content="0" />
    </head>
    <body>
        @using (Html.BeginForm("SubmitPayment", "Payments"))
        {
            <div class="widthSize">
                <div class="outerBox">
                    <table>
                        <tr>
                            <td class="rightSide">
                                @Html.DisplayNameFor(model => model.Name)
                            </td>
                            <td class="leftSide">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                        </tr>

                        <tr>
                            <td class="rightSide">
                                @Html.DisplayNameFor(model => model.Email)
                            </td>
                            <td class="leftSide">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", type = "email" } })

                            </td>
                        </tr>

                        <tr>
                            <td class="rightSide">
                                @Html.DisplayNameFor(model => model.CardNumber)
                            </td>
                            <td class="leftSide">
                                @Html.EditorFor(model => model.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
                            </td>
                        </tr>

                        <tr>
                            <td class="rightSide">
                                @Html.DisplayNameFor(model => model.CardType)
                            </td>

                            <td class="leftSide">
                                @Html.EnumDropDownListFor(model => model.CardType, "Select", new { @class = "helper-format dropDownBox" })
                            </td>
                        </tr>

                        <tr>
                            <td class="rightSide">
                                <label for="EmailNotification">EmailNotification</label>
                            </td>
                            <td class="leftSide">
                                @Html.EditorFor(model => model.EmailNotification, new { htmlAttributes = new { @class = "form-control regularCheckbox" } })
                            </td>
                        </tr>
                    </table>
                    @Html.ValidationSummary("", new { style = "color: red;" })
                </div>

                <table>
                    <tr class="floatRightSide">
                        <td>
                            <input type="submit" value="Submit order >>" class="genericButton submitButton" />
                        </td>
                    </tr>
                </table>
            </div>
        }
    </body>
    </html>