Website/Models/Movies/BrowsePageConstants.cs
using Sitecore.Data.Items;
using System.Collections.Generic;

namespace Website.Models.Movies
{
    public class BrowsePageConstants
    {
        public static IEnumerable<Item> MovieTitlesAndPrices { get; set; }
        public static Item SubTitleItems { get; set; }

        public static string HomeItem = "/sitecore/Content/Browse";

        public static string MovieNamesItem = "/sitecore/Content/MovieNames";

        public static string PaymentItem = "/sitecore/Content/Payment";
    }
}

Website/Models/Movies/BrowsePageFunctions.cs
using Sitecore.Links;

namespace Website.Models.Movies
{
    public class BrowsePageFunctions
    {
        public static string GetUrlForItem(string Query)
        {
            return LinkManager.GetItemUrl(Sitecore.Context.Database.GetItem(Query));
        }

        public static Sitecore.Data.Items.Item SitecoreDatabase(string Query)
        {
            return Sitecore.Context.Database.GetItem(Query);
        }
    }
}

Website/Models/Movies/Movie.cs
namespace EMovies.Models.Movies
{
    public class Movie
    {
        public string Name { get;  set; }

        public string Description { get;  set; }

        public decimal Price { get;  set; }

        public int Quantity { get; set; }

        public decimal Total { get;  set; }
    }
}

Website/Models/Movies/ShoppingBasket.cs
using System.Collections.Generic;
using System.Linq;

namespace EMovies.Models.Movies
{
    public class ShoppingBasket
    {
        public List<Movie> Movies { get; set; }
        public decimal TotalPrice
        {
            get { return Movies.Select(movie => movie.Quantity * movie.Price).Sum(); }
        }
        public IEnumerable<int> Quantities
        {
            get { return Movies.Select(movie => movie.Quantity); }
        }
        public IEnumerable<decimal> Prices
        {
            get { return Movies.Select(movie => movie.Price); }
        }
        public int TotalQuantity
        {
            get { return Movies.Select(movie => movie.Quantity).Sum(); }
        }
    }
}

Website/Controllers/MoviesController.cs
using EMovies.Models.Movies;
using Sitecore.Data.Items;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.WebPages;
using Website.Models.Movies;

namespace EMovies.Controllers
{
    public class MoviesController : Controller
    {
        public ActionResult Browse()
        {
            ShoppingBasket basket = (ShoppingBasket)Session["Basket"];

            var dataSource = BrowsePageFunctions.SitecoreDatabase(BrowsePageConstants.HomeItem);

            BrowsePageConstants.SubTitleItems = dataSource;

            if (basket == null)
            {
                return View();
            }
            else
            {
                if (basket.TotalQuantity < 1)
                {
                    ModelState.AddModelError("TotalQuantity", "Please add a quantity of at least 1 movie.");
                }
                return View(basket);
            }
        }

        private ShoppingBasket EmptyBasket()
        {
            ShoppingBasket basket = new ShoppingBasket();
            var dataSource = BrowsePageFunctions.SitecoreDatabase(BrowsePageConstants.MovieNamesItem);
            BrowsePageConstants.MovieTitlesAndPrices = dataSource.Children;
            basket.Movies = new List<Movie>();


            if (BrowsePageConstants.MovieTitlesAndPrices != null)
            {
                foreach (Item movie in BrowsePageConstants.MovieTitlesAndPrices)
                {
                    basket.Movies.Add(new Movie { Name = movie.Fields["Title"].ToString(), Price = movie.Fields["Price"].ToString().AsDecimal()});
                }
            }
            else { throw new Exception(); } //Throw 500 error here. Design pages for 404 and 500.

            return basket;
        }

        public ActionResult MovieList()
        {
            ShoppingBasket basket = (ShoppingBasket)Session["Basket"];
            if (basket == null)
            {
                return View(EmptyBasket());
            }
            else
            {
                return View(basket);
            }
        }

        public ActionResult Update(ShoppingBasket basket)
        {
            Session["Basket"] = basket;
           
            return Redirect(BrowsePageFunctions.GetUrlForItem(BrowsePageConstants.HomeItem));
        }

        public ActionResult MoveToPay()
        {
            ShoppingBasket basket;
            basket = (ShoppingBasket)Session["Basket"];

            if (basket == null || basket.TotalQuantity < 1)
            {
                return Redirect(BrowsePageFunctions.GetUrlForItem(BrowsePageConstants.HomeItem));
            }

            return Redirect(BrowsePageFunctions.GetUrlForItem(BrowsePageConstants.PaymentItem));
        }
    }
}

Website/Views/Movies/Browse.cshtml
@using EMovies.Models.Movies;

<html>
<head>
    <META Http-Equiv="Cache-Control" Content="no-cache" />
    <META Http-Equiv="Pragma" Content="no-cache" />
    <META Http-Equiv="Expires" Content="0" />
</head>
<body>

    <div class="widthSize">

        @Html.Sitecore().Placeholder("OrangeBox")

        <table>
            <tr class=whiteBackground>
                <td>
                    <p class=informationBox>Tickets are only valid for use on the day of purchase</p>
                </td>

            </tr>
        </table>

        @Html.ValidationSummary("", new { style = "color: red;" })
    </div>


    @using (Html.BeginForm("MoveToPay", "Movies"))
    {

        <div class="widthSize">

            <table> 

                <tr class=whiteBackground>
                    <td>

                        <input type="submit" value="Order now >>" class="floatRightSide genericButton submitButton" />

                    </td>
                </tr>

            </table>
        </div>
    }

</body>
</html>

Website/Views/Movies/MovieList.cshtml
@using EMovies.Models.Movies;
@model ShoppingBasket
@using Website.Models.Movies;

@using (Html.BeginForm("Update", "Movies"))
{
    <div class="outerBox">

        <table>
            <tr>
                <td>
                    @BrowsePageConstants.SubTitleItems.Fields["Movie"].ToString()
                </td>

                <td>
                    @BrowsePageConstants.SubTitleItems.Fields["Quantity"].ToString()
                </td>

                <td>
                    @BrowsePageConstants.SubTitleItems.Fields["Price"].ToString()
                </td>
            </tr>

            @for (int i = 0; i < Model.Movies.Count(); i++)
            {
                <tr>
                    <td class="blueBox">
                        @Html.DisplayFor(modelItem => Model.Movies[i].Name)
                        @Html.HiddenFor(modelItem => Model.Movies[i].Name)

                    </td>

                    <td class="whiteBoxBlueBorder">
                        @Html.EditorFor(modelItem => Model.Movies[i].Quantity, new { htmlAttributes = new { @class = "form-control", @min = "0" } })
                    </td>
                    <td class="blueBox">
                        @Html.DisplayFor(modelItem => Model.Movies[i].Price)
                        @Html.HiddenFor(modelItem => Model.Movies[i].Price)

                    </td>

                </tr>

            }

        </table>
        <table>
            <tr>
                <td>
                    <p class="floatRightSide bold">@BrowsePageConstants.SubTitleItems.Fields["Total"].ToString() £@Model.TotalPrice</p>
                </td>

            </tr>

            <tr>

                <td>
                    <input type="submit" value="Update" class="floatRightSide genericButton updateButton" />
                </td>

            </tr>


        </table>

    </div>

}